[package]
name = "hyper-body-utils"
version = "0.1.4"
edition = "2021"
authors = ["Rogerio Ara√∫jo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/hyper-body-utils"
homepage = "https://github.com/ararog/hyper-body-utils"
description = "Utilities for handling HTTP bodies with hyper"
readme = "README.md"
license = "MIT"
keywords = ["http", "hyper", "server", "client"]
publish = true
rust-version = "1.75.0"

[features]
default = ["tokio-rt", "http3"]
tokio-rt = ["tokio/fs", "tokio-util/io"]
smol-rt = []
http3 = ["dep:h3", "dep:h3-quinn"]

[dependencies]
bytes = "1.11.1"
futures = { version = "0.3.32", optional = false, default-features = false}
h3 = { version = "0.0.8", optional = true }
h3-quinn = { version = "0.0.10", optional = true }
http-body-util = "0.1.3"
hyper = "1.8.1"
smol = { version = "2.0.2", optional = false, default-features = false }
tokio = { version = "1.49.0", optional = false, default-features = false }
tokio-util = { version = "0.7.18", optional = false, default-features = false }
